# -*- coding: utf-8 -*-
#
# Anki Simulator Add-on for Anki
# Copyright (C)  2020-2021 giovannihenriksen <https://github.com/giovannihenriksen>
#
# This file was automatically generated by Anki Add-on Builder v0.1.4
# It is subject to the same licensing terms as the rest of the program
# (see the LICENSE file which accompanies this program).
#
# WARNING! All changes made in this file will be lost!

"""
Initializes generated Qt forms/resources
"""

__all__ = [
    "anki_simulator_dialog",
    "support_dialog",
    "about_dialog",
    "manual_dialog"
]

from . import anki_simulator_dialog
from . import support_dialog
from . import about_dialog
from . import manual_dialog
