# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'build/dist/designer/manual_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manual_dialog(object):
    def setupUi(self, manual_dialog):
        manual_dialog.setObjectName("manual_dialog")
        manual_dialog.resize(1181, 784)
        self.verticalLayout = QtWidgets.QVBoxLayout(manual_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(manual_dialog)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.closeButton = QtWidgets.QPushButton(manual_dialog)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton)

        self.retranslateUi(manual_dialog)
        QtCore.QMetaObject.connectSlotsByName(manual_dialog)

    def retranslateUi(self, manual_dialog):
        _translate = QtCore.QCoreApplication.translate
        manual_dialog.setWindowTitle(_translate("manual_dialog", "Anki Simulator Manual"))
        self.textBrowser.setHtml(_translate("manual_dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"ankisimulatormanual\"></a><span style=\" font-size:xx-large; font-weight:600;\">A</span><span style=\" font-size:xx-large; font-weight:600;\">nki Simulator Manual</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"whatisankisimulator\"></a><span style=\" font-size:large; font-weight:600;\">W</span><span style=\" font-size:large; font-weight:600;\">hat is Anki Simulator?</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Anki Simulator is an add-on for Anki that lets you simulate Anki progress over time using your cards, deck options and statistics. You can use it to estimate your future workload or to fine-tune and compare deck options.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"howdoiuseit\"></a><span style=\" font-size:large; font-weight:600;\">H</span><span style=\" font-size:large; font-weight:600;\">ow do I use it?</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Deck options and deck performance should come pre-loaded. Just press simulate to see your first simulation! The Y-axis shows the estimated total number of cards you will see on day X. You can perform multiple simulations with different deck options and performance (retention) rates to compare the long-term results. If you adjust deck options, you should also adequately estimate new corresponding performance rates. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"deckoptions\"></a><span style=\" font-size:large; font-weight:600;\">D</span><span style=\" font-size:large; font-weight:600;\">eck options</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please read the <a href=\"https://docs.ankiweb.net/#/deck-options\"><span style=\" text-decoration: underline; color:#0000ff;\">section about deck options</span></a> in the Anki Manual for definitions of all deck options. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"simulationoptions\"></a><span style=\" font-size:large; font-weight:600;\">S</span><span style=\" font-size:large; font-weight:600;\">imulation options</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Here you can decide whether you want to use the actual cards that belong to your selected deck, simulate additional new cards, or just want to mock a deck that contains an X number of new cards instead. Also, you can choose to exclude/include suspended new cards and overdue cards. Suspended reviews are always excluded. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"performancerates\"></a><span style=\" font-size:large; font-weight:600;\">P</span><span style=\" font-size:large; font-weight:600;\">erformance rates</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">These are your retention rates. This number includes cards that were answered \'good\' and \'easy\', as well as 50% of cards that were answered \'hard\'. If you hover your mouse over the values, you will also see the reliability of the percentages. By default, the rates are based on your performance in the past 365 days. You can change this number of days to any cut-off you prefer in the add-on configurations. You can also exclude cards from retention calculation by tagging them with \'exclude-retention-rate\'. Note: Only accurate retention rates are collected. If the margin of error is higher than 5% (based on the 95% confidence interval), retention rates are ignored. Instead, default performance rates are shown: \'92%\' for learning/lapse steps, and \'90%\' for young and mature cards. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"howaccurateisit\"></a><span style=\" font-size:large; font-weight:600;\">H</span><span style=\" font-size:large; font-weight:600;\">ow accurate is it?</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\';\">Anki Simulator was carefully written to closely match Anki\'s scheduling algorithm. Because the add-on uses your actual cards, deck options and statistics, Anki Simulator is able to produce a personalized simulation. If you provide accurate variables, the simulator should do a good job of giving you a </span><span style=\" font-family:\'Helvetica Neue\'; font-style:italic;\">rough idea</span><span style=\" font-family:\'Helvetica Neue\';\"> of your future workload. Obviously however, long-term outcomes rely on many factors that can\'t be implemented in an add-on. The add-on takes some assumptions that may not be applicable in your situation:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\';\">- It does not take into account pressing the \'hard\' or \'easy\' buttons. The simulator assumes that excluding them both should balance their effects out for a large part. (Also see: \'Performance rates\')</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\';\">- It assumes that your retention rates are correct and will not change in the future, and are the same for every single card of a certain type (learning, lapse, young, mature), regardless of individual difficulty.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\';\">- It assumes that no days are skipped.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"canihelpimproveankisimulator\"></a><span style=\" font-size:large; font-weight:600;\">C</span><span style=\" font-size:large; font-weight:600;\">an I help improve Anki Simulator?</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Of course! Anki Simulator is open-source. Anyone is free to suggest new features, submit issues or file pull requests. You can find the project on <a href=\"https://github.com/giovannihenriksen/Anki-Simulator\"><span style=\" text-decoration: underline; color:#0000ff;\">Github</span></a>.</p></body></html>"))
        self.closeButton.setText(_translate("manual_dialog", "Close"))
