json:{
  "change_justification": "original",
  "extra_css": null,
  "base_font_size": 8.0,
  "font_size_mapping": null,
  "line_height": 0.0,
  "minimum_line_height": 120.0,
  "embed_font_family": null,
  "embed_all_fonts": false,
  "subset_embedded_fonts": false,
  "smarten_punctuation": false,
  "unsmarten_punctuation": false,
  "disable_font_rescaling": false,
  "insert_blank_line": false,
  "remove_paragraph_spacing": false,
  "remove_paragraph_spacing_indent_size": 1.5,
  "insert_blank_line_size": 0.5,
  "input_encoding": null,
  "filter_css": "",
  "expand_css": false,
  "asciiize": false,
  "keep_ligatures": false,
  "linearize_tables": false,
  "transform_css_rules": "[]",
  "transform_html_rules": "[]"
}